site_name: BeProduct Python SDK
site_url: https://python.beproduct.com
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
theme:
  name: readthedocs
    #markdown_extensions:
    #  - pymdownx.highlight
    #  - pymdownx.inlinehilite
    #    #  - pymdownx.superfences
    #  - pymdownx.snippets 
